<style>
    div.paragraph {
        height: auto;
        display: block;
        clear:both;
    }

    div.paragraph a.left {
        float: left;
        margin: 0 6px 6px 0;

    }
    div.paragraph a.right {
        float: right;
        margin: 0 0 6px 6px;
    }

    div.paragraph a.thickbox {
        border: 1px solid white;
        display: block;
        width: 110px;
    }
    div.paragraph a img {
        border: 5px solid black;
        width: 100px;
    }


</style>

<div><h3>Instrumentarium:</h3></div>
<hr>
<div class="paragraph">
    <a href="/img/hardware/img_003.jpg" class="left thickbox"><img src="/img/hardware/img_003.jpg"/></a>
    <p>
        <strong>Aria TS 600</strong> &ndash; to ulubiona gitara Mariusza. Urodziła się w Japonii w 1980 roku w słynnej fabryce Matsumoku. Gryf wykonany został z trzech części klonowych, przekładanych drewnem orzechowym, gryf przechodzi przez cały korpus gitary, podstrunnica jest wykonana z hebanu. Z kolei korpus to dwa piękne kawałki jesionu. Gitara posiada jasne, bardzo przejrzyste brzmienie przypominające Stratocastera, jednak humbuckery dodają brzmieniu pazura i mięsistości. Gitara jest bardzo uniwersalna i świetnie sprawdza się w wielu gatunkach muzyki. To gitara „z duszą” i bardzo długą historią, takich już dziś się nie produkuje.
    </p>
</div>

<div class="paragraph">
    <a href="/img/hardware/img_013.jpg" class="right thickbox"><img src="/img/hardware/img_013.jpg"/></a>
    <p>
        <strong>Mayones Tele a&#39;la Suhr</strong> &ndash; ciekawa propozycja nasze rodzimej firmy z Gdańska. Właściwie gitara jest prototypem wykonanym w latach 90 – tych, który nie wszedł do seryjnej produkcji z racji wysokich kosztów produkcji. Konstrukcja to semi – hollow z bardzo ciekawymi wycięciami nad komorą rezonansową. Zastosowanie gitary z założenia powinno skłaniać się w kierunku jazzu, ale do końca tak nie jest. Podłączona pod lampę z włączonym przesterem nabiera charakteru odwrotnie proporcjonalnego do jej wyglądu. Jednak przy zastosowaniu przetwornika piezo staje się łagodna i delikatna, perfekcyjnie imitująca gitarę akustyczną.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_023.jpg" class="left thickbox"><img src="/img/hardware/img_023.jpg"/></a>

    <p>
        <strong>Skrzypce akustyczne</strong> &ndash; jest to instrument lutniczy z 1989 roku, wykonany przez lutnika Piotra Cieślaka (członek Związku Polskich Artyst&oacute;w Lutnik&oacute;w). Skrzypce posiadają przepiękne głębokie brzmienie wyr&oacute;żniające je wśr&oacute;d całej grupy takich instrument&oacute;w i wystarczy tylko odpowiednio pociągnąć smyczkiem i stają się wspaniałym instrumentem solowym z pięknym krystalicznym dźwiękiem, co sprawia, że nawet najszybsze przebiegi melodyczne są wyraziste i czytelne.
    </p>
</div>
<div class="paragraph">
    <p>
        <strong>Skrzypce elektryczne Silent Violin</strong> &ndash; to znakomity elektryczny instrument smyczkowy wyprodukowany w Japonii. Wykonane są ręcznie z opalanego klonu (szyjka) oraz świerku (płyta wierzchnia). Posiadają kołki i podstrunnicę z mahoniu. Całość wykończona jest w kolorze Black.Podczas gdy akustyczne brzmienie jest ledwo słyszalne, po podłączeniu do nagłośnienia słuchacz może poczuć się jakby był w ogromnej sali koncertowej. Oryginalny procesor firmy Yamaha tworzy bogaty, przestrzennynny pogłos, kt&oacute;ry doskonale imituje charakterystyczne efekty brzmieniowe powstające podczas gry na scenie. Dostępne są trzy tryby: Large Hall, Medium Hall oraz Room.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_011.jpg" class="left thickbox"><img src="/img/hardware/img_011.jpg"/></a>
    <p>
        <strong>Mandolina J&amp;D Brothers</strong> &ndash; mandolina z korpusem z litego drewna, mimo niewielkich rozmiar&oacute;w sporo waży. Posiada zamontowany przetwornik Merlin zrobiony przez pana Zbyszka Wr&oacute;blewskiego. Wielki szacuneczek panie Zbyszku, robi pan najlepsze przetworniki na świecie!
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_002.jpg" class="right thickbox"><img src="/img/hardware/img_002.jpg"/></a>
    <p>
        <strong>Akordeon Delicia Choral VI</strong> &ndash; instrument produkcji czechosłowackiej z 1986 roku, wyposażony w piszczałki Hohnera. Instrument, od kt&oacute;rego zaczęło się muzykowanie Mariusza, kt&oacute;ry posiada go od nowości i właśnie na nim wydobył swoje pierwsze dźwięki, chociaż p&oacute;źniej zakochał się w gitarach. Charakter akordeonu &ndash; lekkie, śpiewne dźwięki jakby zasłyszane na francuskiej ulicy.
    </p>
</div>
<div style="clear:both"></div>
<h3>
    Wzmacniacze:</h3>
<hr>
<div class="paragraph">
    <p>
        <strong>Roland AC 60</strong> &ndash; tranzystorowy wzmacniacz akustyczny, do kt&oacute;rego podłączone są skrzypce elektryczne i mandolina. Bardzo wiernie i miękko przesyła czysty i bogaty dźwięk akustyczny dalej, do słuchaczy. Wzmacnia dźwięk instrument&oacute;w w spos&oacute;b naturalny dla ucha, nieprzerysowany, autentyczny.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_018.jpg" class="left thickbox"><img src="/img/hardware/img_018.jpg"/></a>
    <p>
        <strong>Laney VC30 112</strong> &ndash; w pełni lampowy wzmacniacz gitarowy, niepozorny w wyglądzie, oszałamiający w brzmieniu. Czysta klasyka! Stworzony na wz&oacute;r wzmacniaczy z lat 60-tych.
    </p>
</div>

<div style="clear:both"></div>
<h3>
    Efekty:</h3>
<hr>
<div class="paragraph">
    <a href="/img/hardware/img_012.jpg" class="right thickbox"><img src="/img/hardware/img_012.jpg"/></a>
    <p>
        <strong>Marshall EH-1</strong> &ndash; analogowy delay dający brzmieniu gitary przestrzeni i powietrza. Właściwie nie odpoczywa podczas całego grania.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_028.jpg" class="left thickbox"><img src="/img/hardware/img_028.jpg"/></a>
    <p>
        <strong>Electro-Harmonix</strong> &ndash; analogowy multiefekt wah, wibrato, phase i tremolo. Bardzo fajny i jeszcze bardziej przydatny!
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_026.jpg" class="right thickbox"><img src="/img/hardware/img_026.jpg"/></a>
    <p>
        <strong>Jean-Paul Electronics &micro;AMP2</strong> &ndash; polski, ręcznie wykonany przester typu overdrive mający w swoim repertuarze ciepłe brzmienia bluesowe, crunch, aż po mocne riffy. Także bardzo przydatny, zwłaszcza przy rockowych kawałkach i sol&oacute;wkach.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_005.jpg" class="left thickbox"><img src="/img/hardware/img_005.jpg"/></a>
    <p>
        <strong>Danelectro Cool Cat V2 Transparent Overdrive</strong> &ndash; zwykle ustawiony jest na delikatnym crunchu, mimo to daje Arii sporego kopa.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_004.jpg" class="right thickbox"><img src="/img/hardware/img_004.jpg"/></a>
    <p>
        <strong>Danelectro Cool Cat Chorus</strong> &ndash; daje śliczne lekko &bdquo;rozstrojone&rdquo; brzmienie, niezastąpiony w balladach.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_007.jpg" class="left thickbox"><img src="/img/hardware/img_007.jpg"/></a>
    <p>
        <strong>Danelectro Fab Flange</strong> &ndash; świetnie brzmiący flanger, bez kt&oacute;rego nie można byłoby grać kawałk&oacute;w Lady Pank.
    </p>
</div>

<div style="clear:both"></div>
<div><h3>Nagłośnienie:</h3></div>
<hr>

<div class="paragraph">
    <a href="/img/hardware/img_016.jpg" class="left thickbox"><img src="/img/hardware/img_016.jpg"/></a>
    <p>
        Za dźwięk docierający do bawiących się odpowiadają aktywne kolumny JBL PRX 615M. W nowoczesnej, stosunkowe niewielkiej obudowie zawiera się bardzo duża moc. Dźwięk emitowany przez kolumny jest bardzo przejrzysty, selektywny i klarowny. Zapewnia uczestnikom imprez duży komfort podczas zabawy. Czysty, mocny i zarazem ciepły dźwięk rozchodzi się pod dużym kątem, co powoduje, że dociera do każdego miejsca w sali tanecznej z odpowiednim natężeniem.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_001.jpg" class="right thickbox"><img src="/img/hardware/img_001.jpg"/></a>
    <p>
        W przypadku większej liczby gości, bardzo dużej sali lub imprezy organizowanej na zewnątrz do zestawu satelit dołączany jest subwoofer JBL PRX 618S, kt&oacute;ry nasyca przestrzeń niskimi rejestrami, co czyni pracę zespołu jeszcze przyjemniejszą w odbiorze.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_015.jpg" class="left thickbox"><img src="/img/hardware/img_015.jpg"/></a>
    <p>
        Sercem sterowania jest mikser Soundcraft MFX 12 z efektem Lexicon doskonale wsp&oacute;łpracujący z kolumnami. Wbudowany procesor efekt&oacute;w pozwala wzbogacić brzmienie wokali na przykład przestrzennym reverbem lub subtelnym delayem... jednak tylko lekko, dla ozdoby... bez przesady...
    </p>
    <p>
</div>
<div class="paragraph">
    <!-- a href="/img/hardware/img_003.jpg" class="left thickbox"><img src="/img/hardware/img_003.jpg"/></a -->
    Natomiast w racku działają dwa zamontowane kompresory, kt&oacute;re wyr&oacute;wnują dynamikę wokali. Są to Alesis 3630 i legendarny DBX 266XL. Są to bardzo istotne urządzenia, kt&oacute;re powodują, że dźwięk jest okrągły, bardziej uwypuklony i nie brzmiący krzykliwie. Poza tym kompresory działają jeszcze jako brama szum&oacute;w.
</p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_017.jpg" class="left thickbox"><img src="/img/hardware/img_017.jpg"/></a>
    <p>
        Dwie aktywne kolumny DB Technologies Basic DJ pełnią rolę odsłuch&oacute;w i odwr&oacute;cone są w stronę zespołu.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_014.jpg" class="right thickbox"><img src="/img/hardware/img_014.jpg"/></a>
    <p>
        Korzystamy z mikrofon&oacute;w Shure SM 58 i Beta 58A, Shure bezprzewodowy PG30, AKG bezprzewodowy WM 40.
    </p>
</div>

<div style="clear:both"></div>
<h3>Oświetlenie:</h3>
<hr>

<div class="paragraph">
    <a href="/img/hardware/img_027.jpg" class="left thickbox"><img src="/img/hardware/img_027.jpg"/></a>

    <p>
        <strong>American DJ Vertigo</strong> &ndash; klasyczny &bdquo;grzybek&rdquo;, efekt LED - owy produkujący bardzo nasycone kolory: czerwony, zielony, niebieski, purpurowy, ż&oacute;łty, cyjankowy oraz biały.
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_021.jpg" class="right thickbox"><img src="/img/hardware/img_021.jpg"/></a>
    <p>
        <strong>American DJ Revo III</strong> &ndash; to prawdziwa rewolucja jeśli chodzi o oświetlenie parkietu! Jest to potężny LED &ndash; owy reflektor posiadający 392 diody świecące w kolorach czerwonym, niebieskim, zielonym i białym. Efekt daje dużo światła i jest przy tym bardzo przyjemny i ciepły.
        <a href="http://www.youtube.com/watch?v=SpiXbv3yobw">http://www.youtube.com/watch?v=SpiXbv3yobw</a>
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_009.jpg" class="left thickbox"><img src="/img/hardware/img_009.jpg"/></a>
    <p>
        <strong>American DJ Galaxian 3D</strong> &ndash; dwukolorowy laser emitujący ponad 500 promieni. Te właśnie promienie wyglądają na parkiecie jak tlące się iskierki, kt&oacute;re nieustannie zmieniają swoje położenie tworząc nieustannie zmieniające się tr&oacute;jwymiarowe kompozycje.
    </p><p>
        <a href="http://www.youtube.com/watch?v=-kcu0uBGF2Y">http://www.youtube.com/watch?v=-kcu0uBGF2Y</a>
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_010.jpg" class="right thickbox"><img src="/img/hardware/img_010.jpg"/></a>
    <p>
        <strong>American DJ H2O</strong> &ndash; jak sama nazwa wskazuje &ndash; woda. Także LED &ndash; owa imitacja płynącej wody w kolorach: pomarańczowym, zielonym, niebieskim, ż&oacute;łtym, purpurowym, białym. Efekt jest niezmiernie estetyczny i kojąco wpływa na ewentualnie zszargane nerwy...
    </p>
    <p>
        <a href="http://www.youtube.com/watch?v=RefofpVIsDc">http://www.youtube.com/watch?v=RefofpVIsDc</a>
    </p>
</div>
<div class="paragraph">
    <a href="/img/hardware/img_006.jpg" class="left thickbox"><img src="/img/hardware/img_006.jpg"/></a>
    <p>
        <strong>Antari F80 Z</strong> &ndash; wytwornica dymu, kt&oacute;ra potrafi nieźle &bdquo;zadymić&rdquo;, ale przede wszystkim powoduje, że reszta efekt&oacute;w jest widoczna w powietrzu.
    </p>
</div>