<style>
    .loginWindow {
        padding: 60px;
        margin: 100px auto;
        border: 1px solid #dddddd;
        width: 200px;
        height: 150px;
        background: #fefefe; /* Old browsers */
        background: -moz-linear-gradient(top,  #fefefe 0%, #e7e4e1 100%); /* FF3.6+ */
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fefefe), color-stop(100%,#e7e4e1)); /* Chrome,Safari4+ */
        background: -webkit-linear-gradient(top,  #fefefe 0%,#e7e4e1 100%); /* Chrome10+,Safari5.1+ */
        background: -o-linear-gradient(top,  #fefefe 0%,#e7e4e1 100%); /* Opera 11.10+ */
        background: -ms-linear-gradient(top,  #fefefe 0%,#e7e4e1 100%); /* IE10+ */
        background: linear-gradient(top,  #fefefe 0%,#e7e4e1 100%); /* W3C */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fefefe', endColorstr='#e7e4e1',GradientType=0 ); /* IE6-9 */
    }

    #email-label, #password-label {
        font-size: 12px;
        height: 30px;
        line-height: 30px;
    }
</style>

<div class="container_16">
    <div class="loginWindow">
        <?php echo $this->form; ?>
    </div>
</div>