<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link href="/css/960.css" rel="stylesheet" />
        <link href="/css/admin.css" rel="stylesheet" />
        <title>Szaron Stoun - panel administracyjny</title>
    </head>
    <body>
        <header>
            <img src="/img/logoszst.png" />
            <span id="header_panel">Panel administracji</span>
            <span id="header_login">Witaj, <?= $this->layout()->username; ?>! &nbsp;</span>
        </header>
        <nav id="menu">
            <ul>
                <li><a href="/logout" style="height: 20px; line-height: 30px;">Wyloguj</a></li>
            </ul>
        </nav>


        <div id="main">
            <article class="container_16">
                <?php echo $this->layout()->content; ?>
            </article>
        </div>
        <footer>
            <div>
                Panel zarządzania treścią<br />
                Sally Yumeno &copy; <?= date('Y'); ?><br />
                developed by <a href="http://dende.com.pl">Dende</a>
            </div>
        </footer>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.6.2.min.js"><\/script>')</script>
        <script src="/js/libs/modernizr-2.0.6.min.js"></script>
        <script src="/js/ckeditor/ckeditor.js"></script>
        <script src="/js/ckeditor/adapters/jquery.js"></script>

        <?= $this->headScript(); ?>
    </body>
</html>
