<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <?= $this->headTitle($this->headTitle)->setSeparator(" - "); ?>
        <meta name="description" content="<?= $this->headDescription; ?>">
        <meta name="author" content="Grzegorz 'Uirapuru' Kaszuba - dende.com.pl">

        <meta name="viewport" content="width=device-width,initial-scale=1">

        <!-- CSS concatenated and minified via ant build script-->
        <link rel="stylesheet" href="/css/thickbox.css">
        <link rel="stylesheet" href="/css/style.css">
        <!-- end CSS-->


    </head>

    <body>

        <div id="container">
            <header>
                <img src="/img/logoszst.png" />
            </header>
            <div id="main" role="main">
                <div id="wrapper">
                    <?
                    $iKey = 0;
                    $oContainer = $this->navigation()->getContainer();
                    ?>
                    <? foreach ($oContainer as $oPage): ?>
                        <?
                        if (!$oPage->isVisible()) {
                            continue;
                        }
                        ?>
                        <div class="panelset<?= $oPage->isActive() ? ' opened' : '' ?>" style="left: <?= ($iKey++ * 41 * -1) . 'px' ?>">
                            <div class="big-button">
                                <a href="<?= $oPage->getHref(); ?>"><?= $oPage->getLabel(); ?></a>
                                <div class="bg-normal"></div>
                                <div class="bg-active"></div>
                            </div>
                            <div class="content-panel"></div>
                            <img src="/img/shadow.png" class="bottom-shadow"/>
                        </div>
                    <? endforeach; ?>                  
                    <div class="clearfix"></div>
                </div>
                <div id="content" class="<?= $oContainer->findOneBy("active", true) !== null ? "" : "hidden" ?>">
                    <?= $this->layout()->content; ?>
                </div>
            </div>
            <footer>
                <? /*
                  <nav class="hidden">
                  <a href="#" id="prev">&laquo;</a>
                  <a href="#" id="next">&raquo;</a>
                  </nav>
                 * 
                 */ ?>

                <span class="author">by <a href="http://www.dende.com.pl">dende.com.pl</a></span>
            </footer>
        </div> <!--! end of #container -->


        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')</script>
        <script src="js/libs/modernizr-2.0.6.min.js"></script>
        <script src="js/libs/cufon-yui.js" type="text/javascript"></script>
        <script src="js/libs/Teen_Light_400.font.js" type="text/javascript"></script>
        <script src="js/libs/jquery.history.js" type="text/javascript"></script>
        <script src="/js/jquery.thickbox.js" type="text/javascript"></script>
        <!-- scripts concatenated and minified via ant build script-->
        <script defer src="js/script.js"></script>
        <!-- end scripts-->


        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-28838234-1']);
            _gaq.push(['_setDomainName', 'szaronstoun.pl']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>


        <!--[if lt IE 7 ]>
          <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
          <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
        <![endif]-->

    </body>
</html>
